on: push
name: Tests
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: cedrickring/golang-action/go1.14@1.6.0
      env:
        GO111MODULE: "on"
        IMPORT: "lyft/atlantis"
      with:
        args: make test